// ============================================================================
// internal.conf.v1 — Bootstrap configuration schema
// ============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: internal/conf/v1/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`     // server configuration (HTTP/GRPC)
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`         // data storage, brokers and etc.
	App           *App                   `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`           // application metadata
	Webhooks      *Webhooks              `protobuf:"bytes,4,opt,name=webhooks,proto3" json:"webhooks,omitempty"` // webhooks configuration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *Bootstrap) GetWebhooks() *Webhooks {
	if x != nil {
		return x.Webhooks
	}
	return nil
}

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`       // mode of operation (dev/prod/etc.)
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       // application name
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // application version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{1}
}

func (x *App) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --------------------------------------------------------------------------
	// 3.x) Instances of servers
	// --------------------------------------------------------------------------
	Http          *Server_HTTP `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --------------------------------------------------------------------------
	// 4.x) Components of Data
	// --------------------------------------------------------------------------
	Database      *Data_Database `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Mqtt          *MQTT          `protobuf:"bytes,2,opt,name=mqtt,proto3" json:"mqtt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetMqtt() *MQTT {
	if x != nil {
		return x.Mqtt
	}
	return nil
}

type MQTT struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Active               bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`                                                          // is MQTT active
	Source               string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`                                                           // URI/source
	ClientId             string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                                       // client identifier
	MaxReconnectInterval *durationpb.Duration   `protobuf:"bytes,4,opt,name=max_reconnect_interval,json=maxReconnectInterval,proto3" json:"max_reconnect_interval,omitempty"` // maximum reconnect interval
	Topics               []string               `protobuf:"bytes,5,rep,name=topics,proto3" json:"topics,omitempty"`                                                           // topics for subscription
	Publish              *Publish               `protobuf:"bytes,6,opt,name=publish,proto3" json:"publish,omitempty"`                                                         // publication settings
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MQTT) Reset() {
	*x = MQTT{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MQTT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MQTT) ProtoMessage() {}

func (x *MQTT) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MQTT.ProtoReflect.Descriptor instead.
func (*MQTT) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{4}
}

func (x *MQTT) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *MQTT) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MQTT) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MQTT) GetMaxReconnectInterval() *durationpb.Duration {
	if x != nil {
		return x.MaxReconnectInterval
	}
	return nil
}

func (x *MQTT) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *MQTT) GetPublish() *Publish {
	if x != nil {
		return x.Publish
	}
	return nil
}

type Publish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic1        string                 `protobuf:"bytes,1,opt,name=topic1,proto3" json:"topic1,omitempty"`
	Topic2        string                 `protobuf:"bytes,2,opt,name=topic2,proto3" json:"topic2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publish) Reset() {
	*x = Publish{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publish) ProtoMessage() {}

func (x *Publish) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publish.ProtoReflect.Descriptor instead.
func (*Publish) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Publish) GetTopic1() string {
	if x != nil {
		return x.Topic1
	}
	return ""
}

func (x *Publish) GetTopic2() string {
	if x != nil {
		return x.Topic2
	}
	return ""
}

type Webhooks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhook       *Webhook               `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Webhooks) Reset() {
	*x = Webhooks{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webhooks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webhooks) ProtoMessage() {}

func (x *Webhooks) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webhooks.ProtoReflect.Descriptor instead.
func (*Webhooks) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Webhooks) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

type Webhook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`         // base URL of the webhook
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"` // timeout of the webhook
	Routes        *Webhook_Routes        `protobuf:"bytes,3,opt,name=routes,proto3" json:"routes,omitempty"`   // routes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Webhook) Reset() {
	*x = Webhook{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webhook) ProtoMessage() {}

func (x *Webhook) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webhook.ProtoReflect.Descriptor instead.
func (*Webhook) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Webhook) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Webhook) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Webhook) GetRoutes() *Webhook_Routes {
	if x != nil {
		return x.Routes
	}
	return nil
}

// --------------------------------------------------------------------------
// 3.1) HTTP — HTTP server
// --------------------------------------------------------------------------
type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"` // for example: "tcp"
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`       // address: ":8080"
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"` // request timeout
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// --------------------------------------------------------------------------
// 3.2) GRPC — gRPC server
// --------------------------------------------------------------------------
type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"` // for example: "tcp"
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`       // address: ":9090"
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"` // request timeout
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// --------------------------------------------------------------------------
// 4.1) Database — database initialization management
// --------------------------------------------------------------------------
type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`         // is database active
	Migrations    bool                   `protobuf:"varint,2,opt,name=migrations,proto3" json:"migrations,omitempty"` // apply migrations
	Seed          bool                   `protobuf:"varint,3,opt,name=seed,proto3" json:"seed,omitempty"`             // fill with initial data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Data_Database) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Data_Database) GetMigrations() bool {
	if x != nil {
		return x.Migrations
	}
	return false
}

func (x *Data_Database) GetSeed() bool {
	if x != nil {
		return x.Seed
	}
	return false
}

// --------------------------------------------------------------------------
// 6.1) List of routes (example)
// --------------------------------------------------------------------------
type Webhook_Routes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route1        string                 `protobuf:"bytes,1,opt,name=route1,proto3" json:"route1,omitempty"`
	Route2        string                 `protobuf:"bytes,2,opt,name=route2,proto3" json:"route2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Webhook_Routes) Reset() {
	*x = Webhook_Routes{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webhook_Routes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webhook_Routes) ProtoMessage() {}

func (x *Webhook_Routes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webhook_Routes.ProtoReflect.Descriptor instead.
func (*Webhook_Routes) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{7, 0}
}

func (x *Webhook_Routes) GetRoute1() string {
	if x != nil {
		return x.Route1
	}
	return ""
}

func (x *Webhook_Routes) GetRoute2() string {
	if x != nil {
		return x.Route2
	}
	return ""
}

var File_internal_conf_v1_conf_proto protoreflect.FileDescriptor

const file_internal_conf_v1_conf_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/conf/v1/conf.proto\x12\x10internal.conf.v1\x1a\x1egoogle/protobuf/duration.proto\"\xca\x01\n" +
	"\tBootstrap\x120\n" +
	"\x06server\x18\x01 \x01(\v2\x18.internal.conf.v1.ServerR\x06server\x12*\n" +
	"\x04data\x18\x02 \x01(\v2\x16.internal.conf.v1.DataR\x04data\x12'\n" +
	"\x03app\x18\x03 \x01(\v2\x15.internal.conf.v1.AppR\x03app\x126\n" +
	"\bwebhooks\x18\x04 \x01(\v2\x1a.internal.conf.v1.WebhooksR\bwebhooks\"G\n" +
	"\x03App\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xc4\x02\n" +
	"\x06Server\x121\n" +
	"\x04http\x18\x01 \x01(\v2\x1d.internal.conf.v1.Server.HTTPR\x04http\x121\n" +
	"\x04grpc\x18\x02 \x01(\v2\x1d.internal.conf.v1.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xc7\x01\n" +
	"\x04Data\x12;\n" +
	"\bdatabase\x18\x01 \x01(\v2\x1f.internal.conf.v1.Data.DatabaseR\bdatabase\x12*\n" +
	"\x04mqtt\x18\x02 \x01(\v2\x16.internal.conf.v1.MQTTR\x04mqtt\x1aV\n" +
	"\bDatabase\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x1e\n" +
	"\n" +
	"migrations\x18\x02 \x01(\bR\n" +
	"migrations\x12\x12\n" +
	"\x04seed\x18\x03 \x01(\bR\x04seed\"\xf1\x01\n" +
	"\x04MQTT\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12O\n" +
	"\x16max_reconnect_interval\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x14maxReconnectInterval\x12\x16\n" +
	"\x06topics\x18\x05 \x03(\tR\x06topics\x123\n" +
	"\apublish\x18\x06 \x01(\v2\x19.internal.conf.v1.PublishR\apublish\"9\n" +
	"\aPublish\x12\x16\n" +
	"\x06topic1\x18\x01 \x01(\tR\x06topic1\x12\x16\n" +
	"\x06topic2\x18\x02 \x01(\tR\x06topic2\"?\n" +
	"\bWebhooks\x123\n" +
	"\awebhook\x18\x01 \x01(\v2\x19.internal.conf.v1.WebhookR\awebhook\"\xc4\x01\n" +
	"\aWebhook\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x128\n" +
	"\x06routes\x18\x03 \x01(\v2 .internal.conf.v1.Webhook.RoutesR\x06routes\x1a8\n" +
	"\x06Routes\x12\x16\n" +
	"\x06route1\x18\x01 \x01(\tR\x06route1\x12\x16\n" +
	"\x06route2\x18\x02 \x01(\tR\x06route2B\x1fZ\x1dservice/internal/conf/v1;confb\x06proto3"

var (
	file_internal_conf_v1_conf_proto_rawDescOnce sync.Once
	file_internal_conf_v1_conf_proto_rawDescData []byte
)

func file_internal_conf_v1_conf_proto_rawDescGZIP() []byte {
	file_internal_conf_v1_conf_proto_rawDescOnce.Do(func() {
		file_internal_conf_v1_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_conf_v1_conf_proto_rawDesc), len(file_internal_conf_v1_conf_proto_rawDesc)))
	})
	return file_internal_conf_v1_conf_proto_rawDescData
}

var file_internal_conf_v1_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_conf_v1_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: internal.conf.v1.Bootstrap
	(*App)(nil),                 // 1: internal.conf.v1.App
	(*Server)(nil),              // 2: internal.conf.v1.Server
	(*Data)(nil),                // 3: internal.conf.v1.Data
	(*MQTT)(nil),                // 4: internal.conf.v1.MQTT
	(*Publish)(nil),             // 5: internal.conf.v1.Publish
	(*Webhooks)(nil),            // 6: internal.conf.v1.Webhooks
	(*Webhook)(nil),             // 7: internal.conf.v1.Webhook
	(*Server_HTTP)(nil),         // 8: internal.conf.v1.Server.HTTP
	(*Server_GRPC)(nil),         // 9: internal.conf.v1.Server.GRPC
	(*Data_Database)(nil),       // 10: internal.conf.v1.Data.Database
	(*Webhook_Routes)(nil),      // 11: internal.conf.v1.Webhook.Routes
	(*durationpb.Duration)(nil), // 12: google.protobuf.Duration
}
var file_internal_conf_v1_conf_proto_depIdxs = []int32{
	2,  // 0: internal.conf.v1.Bootstrap.server:type_name -> internal.conf.v1.Server
	3,  // 1: internal.conf.v1.Bootstrap.data:type_name -> internal.conf.v1.Data
	1,  // 2: internal.conf.v1.Bootstrap.app:type_name -> internal.conf.v1.App
	6,  // 3: internal.conf.v1.Bootstrap.webhooks:type_name -> internal.conf.v1.Webhooks
	8,  // 4: internal.conf.v1.Server.http:type_name -> internal.conf.v1.Server.HTTP
	9,  // 5: internal.conf.v1.Server.grpc:type_name -> internal.conf.v1.Server.GRPC
	10, // 6: internal.conf.v1.Data.database:type_name -> internal.conf.v1.Data.Database
	4,  // 7: internal.conf.v1.Data.mqtt:type_name -> internal.conf.v1.MQTT
	12, // 8: internal.conf.v1.MQTT.max_reconnect_interval:type_name -> google.protobuf.Duration
	5,  // 9: internal.conf.v1.MQTT.publish:type_name -> internal.conf.v1.Publish
	7,  // 10: internal.conf.v1.Webhooks.webhook:type_name -> internal.conf.v1.Webhook
	12, // 11: internal.conf.v1.Webhook.timeout:type_name -> google.protobuf.Duration
	11, // 12: internal.conf.v1.Webhook.routes:type_name -> internal.conf.v1.Webhook.Routes
	12, // 13: internal.conf.v1.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	12, // 14: internal.conf.v1.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_internal_conf_v1_conf_proto_init() }
func file_internal_conf_v1_conf_proto_init() {
	if File_internal_conf_v1_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_conf_v1_conf_proto_rawDesc), len(file_internal_conf_v1_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_conf_v1_conf_proto_goTypes,
		DependencyIndexes: file_internal_conf_v1_conf_proto_depIdxs,
		MessageInfos:      file_internal_conf_v1_conf_proto_msgTypes,
	}.Build()
	File_internal_conf_v1_conf_proto = out.File
	file_internal_conf_v1_conf_proto_goTypes = nil
	file_internal_conf_v1_conf_proto_depIdxs = nil
}
