// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: internal/conf/v1/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap Es la configuración principal de la aplicación
type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	App           *App                   `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

// App Es la configuración de la aplicación
type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{1}
}

func (x *App) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Server Es la configuración del servidor
type Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aqui se define el servidor HTTP y GRPC
	Http          *Server_HTTP `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

// Data Es la configuración de la base de datos y Redis&MQTT
type Data struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aqui se define la base de datos y Redis&MQTT
	Database *Data_Database `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// Redis redis = 2;
	Mqtt          *Data_MQTT `protobuf:"bytes,3,opt,name=mqtt,proto3" json:"mqtt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetMqtt() *Data_MQTT {
	if x != nil {
		return x.Mqtt
	}
	return nil
}

// HTTP Es la configuración del servidor HTTP
type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// GRPC Es la configuración del servidor GRPC
type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// Database Es la configuración de la base de datos
type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	EnsureSchema  bool                   `protobuf:"varint,3,opt,name=ensure_schema,json=ensureSchema,proto3" json:"ensure_schema,omitempty"`
	Migrations    bool                   `protobuf:"varint,4,opt,name=migrations,proto3" json:"migrations,omitempty"`
	Seed          bool                   `protobuf:"varint,5,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_Database) GetEnsureSchema() bool {
	if x != nil {
		return x.EnsureSchema
	}
	return false
}

func (x *Data_Database) GetMigrations() bool {
	if x != nil {
		return x.Migrations
	}
	return false
}

func (x *Data_Database) GetSeed() bool {
	if x != nil {
		return x.Seed
	}
	return false
}

// Redis Es la configuración del servidor Redis
// message Redis {
//   string network = 1;
//   string addr = 2;
//   google.protobuf.Duration read_timeout = 3;
//   google.protobuf.Duration write_timeout = 4;
// }
// MQTT Es la configuración del servidor MQTT
type Data_MQTT struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Source               string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	ClientId             string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	MaxReconnectInterval *durationpb.Duration   `protobuf:"bytes,3,opt,name=max_reconnect_interval,json=maxReconnectInterval,proto3" json:"max_reconnect_interval,omitempty"`
	Topics               []string               `protobuf:"bytes,4,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Data_MQTT) Reset() {
	*x = Data_MQTT{}
	mi := &file_internal_conf_v1_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_MQTT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_MQTT) ProtoMessage() {}

func (x *Data_MQTT) ProtoReflect() protoreflect.Message {
	mi := &file_internal_conf_v1_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_MQTT.ProtoReflect.Descriptor instead.
func (*Data_MQTT) Descriptor() ([]byte, []int) {
	return file_internal_conf_v1_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Data_MQTT) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_MQTT) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Data_MQTT) GetMaxReconnectInterval() *durationpb.Duration {
	if x != nil {
		return x.MaxReconnectInterval
	}
	return nil
}

func (x *Data_MQTT) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

var File_internal_conf_v1_conf_proto protoreflect.FileDescriptor

const file_internal_conf_v1_conf_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/conf/v1/conf.proto\x12\x10internal.conf.v1\x1a\x1egoogle/protobuf/duration.proto\"\x92\x01\n" +
	"\tBootstrap\x120\n" +
	"\x06server\x18\x01 \x01(\v2\x18.internal.conf.v1.ServerR\x06server\x12*\n" +
	"\x04data\x18\x02 \x01(\v2\x16.internal.conf.v1.DataR\x04data\x12'\n" +
	"\x03app\x18\x03 \x01(\v2\x15.internal.conf.v1.AppR\x03app\"G\n" +
	"\x03App\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xc4\x02\n" +
	"\x06Server\x121\n" +
	"\x04http\x18\x01 \x01(\v2\x1d.internal.conf.v1.Server.HTTPR\x04http\x121\n" +
	"\x04grpc\x18\x02 \x01(\v2\x1d.internal.conf.v1.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xb1\x03\n" +
	"\x04Data\x12;\n" +
	"\bdatabase\x18\x01 \x01(\v2\x1f.internal.conf.v1.Data.DatabaseR\bdatabase\x12/\n" +
	"\x04mqtt\x18\x03 \x01(\v2\x1b.internal.conf.v1.Data.MQTTR\x04mqtt\x1a\x93\x01\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12#\n" +
	"\rensure_schema\x18\x03 \x01(\bR\fensureSchema\x12\x1e\n" +
	"\n" +
	"migrations\x18\x04 \x01(\bR\n" +
	"migrations\x12\x12\n" +
	"\x04seed\x18\x05 \x01(\bR\x04seed\x1a\xa4\x01\n" +
	"\x04MQTT\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12O\n" +
	"\x16max_reconnect_interval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x14maxReconnectInterval\x12\x16\n" +
	"\x06topics\x18\x04 \x03(\tR\x06topicsB\x1fZ\x1dservice/internal/conf/v1;confb\x06proto3"

var (
	file_internal_conf_v1_conf_proto_rawDescOnce sync.Once
	file_internal_conf_v1_conf_proto_rawDescData []byte
)

func file_internal_conf_v1_conf_proto_rawDescGZIP() []byte {
	file_internal_conf_v1_conf_proto_rawDescOnce.Do(func() {
		file_internal_conf_v1_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_conf_v1_conf_proto_rawDesc), len(file_internal_conf_v1_conf_proto_rawDesc)))
	})
	return file_internal_conf_v1_conf_proto_rawDescData
}

var file_internal_conf_v1_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_conf_v1_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: internal.conf.v1.Bootstrap
	(*App)(nil),                 // 1: internal.conf.v1.App
	(*Server)(nil),              // 2: internal.conf.v1.Server
	(*Data)(nil),                // 3: internal.conf.v1.Data
	(*Server_HTTP)(nil),         // 4: internal.conf.v1.Server.HTTP
	(*Server_GRPC)(nil),         // 5: internal.conf.v1.Server.GRPC
	(*Data_Database)(nil),       // 6: internal.conf.v1.Data.Database
	(*Data_MQTT)(nil),           // 7: internal.conf.v1.Data.MQTT
	(*durationpb.Duration)(nil), // 8: google.protobuf.Duration
}
var file_internal_conf_v1_conf_proto_depIdxs = []int32{
	2,  // 0: internal.conf.v1.Bootstrap.server:type_name -> internal.conf.v1.Server
	3,  // 1: internal.conf.v1.Bootstrap.data:type_name -> internal.conf.v1.Data
	1,  // 2: internal.conf.v1.Bootstrap.app:type_name -> internal.conf.v1.App
	4,  // 3: internal.conf.v1.Server.http:type_name -> internal.conf.v1.Server.HTTP
	5,  // 4: internal.conf.v1.Server.grpc:type_name -> internal.conf.v1.Server.GRPC
	6,  // 5: internal.conf.v1.Data.database:type_name -> internal.conf.v1.Data.Database
	7,  // 6: internal.conf.v1.Data.mqtt:type_name -> internal.conf.v1.Data.MQTT
	8,  // 7: internal.conf.v1.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	8,  // 8: internal.conf.v1.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	8,  // 9: internal.conf.v1.Data.MQTT.max_reconnect_interval:type_name -> google.protobuf.Duration
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_conf_v1_conf_proto_init() }
func file_internal_conf_v1_conf_proto_init() {
	if File_internal_conf_v1_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_conf_v1_conf_proto_rawDesc), len(file_internal_conf_v1_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_conf_v1_conf_proto_goTypes,
		DependencyIndexes: file_internal_conf_v1_conf_proto_depIdxs,
		MessageInfos:      file_internal_conf_v1_conf_proto_msgTypes,
	}.Build()
	File_internal_conf_v1_conf_proto = out.File
	file_internal_conf_v1_conf_proto_goTypes = nil
	file_internal_conf_v1_conf_proto_depIdxs = nil
}
