// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/template/v1/template.proto

package template

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Templatev1Service_ListTemplates_FullMethodName      = "/api.template.v1.Templatev1Service/ListTemplates"
	Templatev1Service_UpsertTemplate_FullMethodName     = "/api.template.v1.Templatev1Service/UpsertTemplate"
	Templatev1Service_DeleteTemplateById_FullMethodName = "/api.template.v1.Templatev1Service/DeleteTemplateById"
)

// Templatev1ServiceClient is the client API for Templatev1Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// * API para gestión de plantillas (alertas/avisos).
type Templatev1ServiceClient interface {
	//* Lista todas las plantillas.
	//
	// **Descripción**
	// Devuelve el catálogo completo de plantillas definidas.
	//
	// **Parámetros**
	// _(sin parámetros)_
	//
	// **Respuestas**
	// - `200 OK`: `templates` + `meta.code = OK`
	// - `200` con error lógico: `meta.code != OK` y `meta.message`
	//
	// **Ejemplos**
	// `GET /template`
	ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error)
	//* Crea o actualiza una plantilla (upsert).
	//
	// **Descripción**
	// Si `id` es `0` o no se envía → crea; si `id` > 0 → actualiza.
	//
	// **Parámetros (body JSON)**
	// - `id` (opcional, 0=create)
	// - `name` (**obligatorio**)
	//
	// **Respuestas**
	// - `200 OK`: `template` resultante + `meta.code = OK`
	// - `200` con error lógico: validación, duplicidad de `name`, etc.
	//
	// **Ejemplos**
	// `POST /template`
	// Body: `{ "name":"Template 1" }`
	UpsertTemplate(ctx context.Context, in *UpsertTemplateRequest, opts ...grpc.CallOption) (*UpsertTemplateResponse, error)
	//* Elimina una plantilla por ID.
	//
	// **Descripción**
	// Borra la plantilla indicada por `id`.
	//
	// **Parámetros (query)**
	// - `id` (**obligatorio**): ID interno
	//
	// **Respuestas**
	// - `200 OK`: `meta.code = OK`
	// - `200` con error lógico: `meta.code != OK` (p. ej., ID inexistente)
	//
	// **Ejemplos**
	// `DELETE /template?id=123`
	DeleteTemplateById(ctx context.Context, in *DeleteTemplateByIdRequest, opts ...grpc.CallOption) (*DeleteTemplateByIdResponse, error)
}

type templatev1ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplatev1ServiceClient(cc grpc.ClientConnInterface) Templatev1ServiceClient {
	return &templatev1ServiceClient{cc}
}

func (c *templatev1ServiceClient) ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplatesResponse)
	err := c.cc.Invoke(ctx, Templatev1Service_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatev1ServiceClient) UpsertTemplate(ctx context.Context, in *UpsertTemplateRequest, opts ...grpc.CallOption) (*UpsertTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertTemplateResponse)
	err := c.cc.Invoke(ctx, Templatev1Service_UpsertTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatev1ServiceClient) DeleteTemplateById(ctx context.Context, in *DeleteTemplateByIdRequest, opts ...grpc.CallOption) (*DeleteTemplateByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTemplateByIdResponse)
	err := c.cc.Invoke(ctx, Templatev1Service_DeleteTemplateById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Templatev1ServiceServer is the server API for Templatev1Service service.
// All implementations must embed UnimplementedTemplatev1ServiceServer
// for forward compatibility.
//
// * API para gestión de plantillas (alertas/avisos).
type Templatev1ServiceServer interface {
	//* Lista todas las plantillas.
	//
	// **Descripción**
	// Devuelve el catálogo completo de plantillas definidas.
	//
	// **Parámetros**
	// _(sin parámetros)_
	//
	// **Respuestas**
	// - `200 OK`: `templates` + `meta.code = OK`
	// - `200` con error lógico: `meta.code != OK` y `meta.message`
	//
	// **Ejemplos**
	// `GET /template`
	ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error)
	//* Crea o actualiza una plantilla (upsert).
	//
	// **Descripción**
	// Si `id` es `0` o no se envía → crea; si `id` > 0 → actualiza.
	//
	// **Parámetros (body JSON)**
	// - `id` (opcional, 0=create)
	// - `name` (**obligatorio**)
	//
	// **Respuestas**
	// - `200 OK`: `template` resultante + `meta.code = OK`
	// - `200` con error lógico: validación, duplicidad de `name`, etc.
	//
	// **Ejemplos**
	// `POST /template`
	// Body: `{ "name":"Template 1" }`
	UpsertTemplate(context.Context, *UpsertTemplateRequest) (*UpsertTemplateResponse, error)
	//* Elimina una plantilla por ID.
	//
	// **Descripción**
	// Borra la plantilla indicada por `id`.
	//
	// **Parámetros (query)**
	// - `id` (**obligatorio**): ID interno
	//
	// **Respuestas**
	// - `200 OK`: `meta.code = OK`
	// - `200` con error lógico: `meta.code != OK` (p. ej., ID inexistente)
	//
	// **Ejemplos**
	// `DELETE /template?id=123`
	DeleteTemplateById(context.Context, *DeleteTemplateByIdRequest) (*DeleteTemplateByIdResponse, error)
	mustEmbedUnimplementedTemplatev1ServiceServer()
}

// UnimplementedTemplatev1ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemplatev1ServiceServer struct{}

func (UnimplementedTemplatev1ServiceServer) ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedTemplatev1ServiceServer) UpsertTemplate(context.Context, *UpsertTemplateRequest) (*UpsertTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertTemplate not implemented")
}
func (UnimplementedTemplatev1ServiceServer) DeleteTemplateById(context.Context, *DeleteTemplateByIdRequest) (*DeleteTemplateByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTemplateById not implemented")
}
func (UnimplementedTemplatev1ServiceServer) mustEmbedUnimplementedTemplatev1ServiceServer() {}
func (UnimplementedTemplatev1ServiceServer) testEmbeddedByValue()                           {}

// UnsafeTemplatev1ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Templatev1ServiceServer will
// result in compilation errors.
type UnsafeTemplatev1ServiceServer interface {
	mustEmbedUnimplementedTemplatev1ServiceServer()
}

func RegisterTemplatev1ServiceServer(s grpc.ServiceRegistrar, srv Templatev1ServiceServer) {
	// If the following call pancis, it indicates UnimplementedTemplatev1ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Templatev1Service_ServiceDesc, srv)
}

func _Templatev1Service_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Templatev1ServiceServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Templatev1Service_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Templatev1ServiceServer).ListTemplates(ctx, req.(*ListTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templatev1Service_UpsertTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Templatev1ServiceServer).UpsertTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Templatev1Service_UpsertTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Templatev1ServiceServer).UpsertTemplate(ctx, req.(*UpsertTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templatev1Service_DeleteTemplateById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Templatev1ServiceServer).DeleteTemplateById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Templatev1Service_DeleteTemplateById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Templatev1ServiceServer).DeleteTemplateById(ctx, req.(*DeleteTemplateByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Templatev1Service_ServiceDesc is the grpc.ServiceDesc for Templatev1Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Templatev1Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.template.v1.Templatev1Service",
	HandlerType: (*Templatev1ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTemplates",
			Handler:    _Templatev1Service_ListTemplates_Handler,
		},
		{
			MethodName: "UpsertTemplate",
			Handler:    _Templatev1Service_UpsertTemplate_Handler,
		},
		{
			MethodName: "DeleteTemplateById",
			Handler:    _Templatev1Service_DeleteTemplateById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/template/v1/template.proto",
}
