// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/errors/error_reason.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common response codes (success + errors)
type ResponseCode int32

const (
	ResponseCode_RESPONSE_CODE_UNSPECIFIED ResponseCode = 0
	// --- Success ---
	ResponseCode_OK       ResponseCode = 200 // 200 OK
	ResponseCode_CREATED  ResponseCode = 201 // 201 Created
	ResponseCode_ACCEPTED ResponseCode = 202 // 202 Accepted
	// --- Client errors ---
	ResponseCode_BAD_REQUEST  ResponseCode = 400 // 400 Invalid Argument
	ResponseCode_UNAUTHORIZED ResponseCode = 401 // 401 Unauthorized
	ResponseCode_FORBIDDEN    ResponseCode = 403 // 403 Forbidden
	ResponseCode_NOT_FOUND    ResponseCode = 404 // 404 Not Found
	ResponseCode_CONFLICT     ResponseCode = 409 // 409 Conflict
	// --- Server errors ---
	ResponseCode_INTERNAL_ERROR      ResponseCode = 500 // 500 Internal Server Error
	ResponseCode_NOT_IMPLEMENTED     ResponseCode = 501 // 501 Not Implemented
	ResponseCode_SERVICE_UNAVAILABLE ResponseCode = 503 // 503 Service Unavailable
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0:   "RESPONSE_CODE_UNSPECIFIED",
		200: "OK",
		201: "CREATED",
		202: "ACCEPTED",
		400: "BAD_REQUEST",
		401: "UNAUTHORIZED",
		403: "FORBIDDEN",
		404: "NOT_FOUND",
		409: "CONFLICT",
		500: "INTERNAL_ERROR",
		501: "NOT_IMPLEMENTED",
		503: "SERVICE_UNAVAILABLE",
	}
	ResponseCode_value = map[string]int32{
		"RESPONSE_CODE_UNSPECIFIED": 0,
		"OK":                        200,
		"CREATED":                   201,
		"ACCEPTED":                  202,
		"BAD_REQUEST":               400,
		"UNAUTHORIZED":              401,
		"FORBIDDEN":                 403,
		"NOT_FOUND":                 404,
		"CONFLICT":                  409,
		"INTERNAL_ERROR":            500,
		"NOT_IMPLEMENTED":           501,
		"SERVICE_UNAVAILABLE":       503,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_errors_error_reason_proto_enumTypes[0].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_api_errors_error_reason_proto_enumTypes[0]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_api_errors_error_reason_proto_rawDescGZIP(), []int{0}
}

// General response format (can be extended)
type StandardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ResponseCode           `protobuf:"varint,1,opt,name=code,proto3,enum=errors.common.ResponseCode" json:"code,omitempty"` // code (success or error)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                            // description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandardResponse) Reset() {
	*x = StandardResponse{}
	mi := &file_api_errors_error_reason_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardResponse) ProtoMessage() {}

func (x *StandardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_errors_error_reason_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardResponse.ProtoReflect.Descriptor instead.
func (*StandardResponse) Descriptor() ([]byte, []int) {
	return file_api_errors_error_reason_proto_rawDescGZIP(), []int{0}
}

func (x *StandardResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_RESPONSE_CODE_UNSPECIFIED
}

func (x *StandardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_errors_error_reason_proto protoreflect.FileDescriptor

const file_api_errors_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/errors/error_reason.proto\x12\rerrors.common\"]\n" +
	"\x10StandardResponse\x12/\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1b.errors.common.ResponseCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xec\x01\n" +
	"\fResponseCode\x12\x1d\n" +
	"\x19RESPONSE_CODE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x02OK\x10\xc8\x01\x12\f\n" +
	"\aCREATED\x10\xc9\x01\x12\r\n" +
	"\bACCEPTED\x10\xca\x01\x12\x10\n" +
	"\vBAD_REQUEST\x10\x90\x03\x12\x11\n" +
	"\fUNAUTHORIZED\x10\x91\x03\x12\x0e\n" +
	"\tFORBIDDEN\x10\x93\x03\x12\x0e\n" +
	"\tNOT_FOUND\x10\x94\x03\x12\r\n" +
	"\bCONFLICT\x10\x99\x03\x12\x13\n" +
	"\x0eINTERNAL_ERROR\x10\xf4\x03\x12\x14\n" +
	"\x0fNOT_IMPLEMENTED\x10\xf5\x03\x12\x18\n" +
	"\x13SERVICE_UNAVAILABLE\x10\xf7\x03B\x1bZ\x19service/api/errors;errorsb\x06proto3"

var (
	file_api_errors_error_reason_proto_rawDescOnce sync.Once
	file_api_errors_error_reason_proto_rawDescData []byte
)

func file_api_errors_error_reason_proto_rawDescGZIP() []byte {
	file_api_errors_error_reason_proto_rawDescOnce.Do(func() {
		file_api_errors_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_errors_error_reason_proto_rawDesc), len(file_api_errors_error_reason_proto_rawDesc)))
	})
	return file_api_errors_error_reason_proto_rawDescData
}

var file_api_errors_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_errors_error_reason_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_errors_error_reason_proto_goTypes = []any{
	(ResponseCode)(0),        // 0: errors.common.ResponseCode
	(*StandardResponse)(nil), // 1: errors.common.StandardResponse
}
var file_api_errors_error_reason_proto_depIdxs = []int32{
	0, // 0: errors.common.StandardResponse.code:type_name -> errors.common.ResponseCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_errors_error_reason_proto_init() }
func file_api_errors_error_reason_proto_init() {
	if File_api_errors_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_errors_error_reason_proto_rawDesc), len(file_api_errors_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_errors_error_reason_proto_goTypes,
		DependencyIndexes: file_api_errors_error_reason_proto_depIdxs,
		EnumInfos:         file_api_errors_error_reason_proto_enumTypes,
		MessageInfos:      file_api_errors_error_reason_proto_msgTypes,
	}.Build()
	File_api_errors_error_reason_proto = out.File
	file_api_errors_error_reason_proto_goTypes = nil
	file_api_errors_error_reason_proto_depIdxs = nil
}
