// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/common/v1/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseCode int32

const (
	ResponseCode_RESPONSE_CODE_UNSPECIFIED           ResponseCode = 0
	ResponseCode_RESPONSE_CODE_OK                    ResponseCode = 200
	ResponseCode_RESPONSE_CODE_NO_CONTENT            ResponseCode = 204
	ResponseCode_RESPONSE_CODE_BAD_REQUEST           ResponseCode = 400
	ResponseCode_RESPONSE_CODE_UNAUTHORIZED          ResponseCode = 401
	ResponseCode_RESPONSE_CODE_FORBIDDEN             ResponseCode = 403
	ResponseCode_RESPONSE_CODE_NOT_FOUND             ResponseCode = 404
	ResponseCode_RESPONSE_CODE_CONFLICT              ResponseCode = 409
	ResponseCode_RESPONSE_CODE_METHOD_NOT_ALLOWED    ResponseCode = 405
	ResponseCode_RESPONSE_CODE_UNPROCESSABLE_ENTITY  ResponseCode = 422
	ResponseCode_RESPONSE_CODE_INTERNAL_SERVER_ERROR ResponseCode = 500
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0:   "RESPONSE_CODE_UNSPECIFIED",
		200: "RESPONSE_CODE_OK",
		204: "RESPONSE_CODE_NO_CONTENT",
		400: "RESPONSE_CODE_BAD_REQUEST",
		401: "RESPONSE_CODE_UNAUTHORIZED",
		403: "RESPONSE_CODE_FORBIDDEN",
		404: "RESPONSE_CODE_NOT_FOUND",
		409: "RESPONSE_CODE_CONFLICT",
		405: "RESPONSE_CODE_METHOD_NOT_ALLOWED",
		422: "RESPONSE_CODE_UNPROCESSABLE_ENTITY",
		500: "RESPONSE_CODE_INTERNAL_SERVER_ERROR",
	}
	ResponseCode_value = map[string]int32{
		"RESPONSE_CODE_UNSPECIFIED":           0,
		"RESPONSE_CODE_OK":                    200,
		"RESPONSE_CODE_NO_CONTENT":            204,
		"RESPONSE_CODE_BAD_REQUEST":           400,
		"RESPONSE_CODE_UNAUTHORIZED":          401,
		"RESPONSE_CODE_FORBIDDEN":             403,
		"RESPONSE_CODE_NOT_FOUND":             404,
		"RESPONSE_CODE_CONFLICT":              409,
		"RESPONSE_CODE_METHOD_NOT_ALLOWED":    405,
		"RESPONSE_CODE_UNPROCESSABLE_ENTITY":  422,
		"RESPONSE_CODE_INTERNAL_SERVER_ERROR": 500,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_api_common_v1_common_proto_enumTypes[0]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{0}
}

type MetaResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    ResponseCode           `protobuf:"varint,1,opt,name=code,proto3,enum=api.common.v1.ResponseCode" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Optional: technical details/field-value for debug in DEV
	Details       map[string]string `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaResponse) Reset() {
	*x = MetaResponse{}
	mi := &file_api_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaResponse) ProtoMessage() {}

func (x *MetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaResponse.ProtoReflect.Descriptor instead.
func (*MetaResponse) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *MetaResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_RESPONSE_CODE_UNSPECIFIED
}

func (x *MetaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MetaResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_api_common_v1_common_proto protoreflect.FileDescriptor

const file_api_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/common/v1/common.proto\x12\rapi.common.v1\"\xd9\x01\n" +
	"\fMetaResponse\x12/\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1b.api.common.v1.ResponseCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12B\n" +
	"\adetails\x18\x03 \x03(\v2(.api.common.v1.MetaResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xf7\x02\n" +
	"\fResponseCode\x12\x1d\n" +
	"\x19RESPONSE_CODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x10RESPONSE_CODE_OK\x10\xc8\x01\x12\x1d\n" +
	"\x18RESPONSE_CODE_NO_CONTENT\x10\xcc\x01\x12\x1e\n" +
	"\x19RESPONSE_CODE_BAD_REQUEST\x10\x90\x03\x12\x1f\n" +
	"\x1aRESPONSE_CODE_UNAUTHORIZED\x10\x91\x03\x12\x1c\n" +
	"\x17RESPONSE_CODE_FORBIDDEN\x10\x93\x03\x12\x1c\n" +
	"\x17RESPONSE_CODE_NOT_FOUND\x10\x94\x03\x12\x1b\n" +
	"\x16RESPONSE_CODE_CONFLICT\x10\x99\x03\x12%\n" +
	" RESPONSE_CODE_METHOD_NOT_ALLOWED\x10\x95\x03\x12'\n" +
	"\"RESPONSE_CODE_UNPROCESSABLE_ENTITY\x10\xa6\x03\x12(\n" +
	"#RESPONSE_CODE_INTERNAL_SERVER_ERROR\x10\xf4\x03B\x1eZ\x1cservice/api/common/v1;commonb\x06proto3"

var (
	file_api_common_v1_common_proto_rawDescOnce sync.Once
	file_api_common_v1_common_proto_rawDescData []byte
)

func file_api_common_v1_common_proto_rawDescGZIP() []byte {
	file_api_common_v1_common_proto_rawDescOnce.Do(func() {
		file_api_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_v1_common_proto_rawDesc), len(file_api_common_v1_common_proto_rawDesc)))
	})
	return file_api_common_v1_common_proto_rawDescData
}

var file_api_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_common_v1_common_proto_goTypes = []any{
	(ResponseCode)(0),    // 0: api.common.v1.ResponseCode
	(*MetaResponse)(nil), // 1: api.common.v1.MetaResponse
	nil,                  // 2: api.common.v1.MetaResponse.DetailsEntry
}
var file_api_common_v1_common_proto_depIdxs = []int32{
	0, // 0: api.common.v1.MetaResponse.code:type_name -> api.common.v1.ResponseCode
	2, // 1: api.common.v1.MetaResponse.details:type_name -> api.common.v1.MetaResponse.DetailsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_common_v1_common_proto_init() }
func file_api_common_v1_common_proto_init() {
	if File_api_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_v1_common_proto_rawDesc), len(file_api_common_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_v1_common_proto_goTypes,
		DependencyIndexes: file_api_common_v1_common_proto_depIdxs,
		EnumInfos:         file_api_common_v1_common_proto_enumTypes,
		MessageInfos:      file_api_common_v1_common_proto_msgTypes,
	}.Build()
	File_api_common_v1_common_proto = out.File
	file_api_common_v1_common_proto_goTypes = nil
	file_api_common_v1_common_proto_depIdxs = nil
}
