app:
  mode: dev
  name: kratos-template
  version: v1

server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    ensure_schema: false
    migrations: false
    seed: false
# redis:
#   addr: 127.0.0.1:6379
#   read_timeout: 0.2s
#   write_timeout: 0.2s
  mqtt:
    source: "tcp://10.70.20.40:1883"
    client_id: "client_kratos_template"
    max_reconnect_interval: "60s"
    topics:
      - "receiver/ltm/#"
      - "receiver/lta/#"
      - "receiver/ltc/#"
      - "receiver/scr/#"
