// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"service/internal/broker"
	"service/internal/conf/v1"
	"service/internal/data"
	"service/internal/feature/prueba/v1"
	"service/internal/feature/prueba/v1/biz"
	"service/internal/feature/prueba/v1/repo"
	"service/internal/feature/prueba/v1/service"
	"service/internal/feature/template/v1"
	"service/internal/feature/template/v1/biz"
	"service/internal/feature/template/v1/repo"
	"service/internal/feature/template/v1/service"
	"service/internal/server/grpc"
	"service/internal/server/http"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(app *conf.App, serverConf *conf.Server, dataConf *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(dataConf, logger)
	if err != nil {
		return nil, nil, err
	}
	templateRepo := template_repo.NewTemplateRepo(dataData, logger)
	templateUsecase := template_biz.NewTemplateUsecase(templateRepo, logger)
	templateService := template_service.NewTemplateService(templateUsecase)
	httpRegister := template.NewTemplatesHTTPRegistrer(templateService)
	pruebaRepo := prueba_repo.NewPruebaRepo(dataData, logger)
	pruebaUsecase := prueba_biz.NewPruebaUsecase(pruebaRepo, logger)
	pruebaService := prueba_service.NewPruebaService(pruebaUsecase)
	pruebaHTTPRegister := prueba.NewPruebaHTTPRegistrer(pruebaService)
	grpcRegister := template.NewTemplatesGRPCRegistrer(templateService)
	pruebaGRPCRegister := prueba.NewPruebaGRPCRegistrer(pruebaService)
	allRegistrers := BuildAllRegistrars(httpRegister, pruebaHTTPRegister, grpcRegister, pruebaGRPCRegister)
	v := ProvideGRPCRegistrers(allRegistrers)
	server := server_grpc.NewGRPCServer(serverConf, v, logger)
	v2 := ProvideHTTPRegistrers(allRegistrers)
	httpServer := server_http.NewHTTPServer(serverConf, v2, logger)
	brokerBroker := broker.NewBroker(templateUsecase, logger)
	kratosApp := newApp(logger, app, server, httpServer, brokerBroker, dataConf)
	return kratosApp, func() {
		cleanup()
	}, nil
}
