// Code generated by protoc-gen-go-http. DO NOT EDIT.

package template

import (
	context "context"
	middleware "github.com/go-kratos/kratos/v2/middleware"
	http1 "github.com/go-kratos/kratos/v2/transport/http"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
// context./http./middleware.
const _ = http1.SupportPackageIsVersion1

type TemplatesHTTPServer interface {
	DeleteTemplateById(context.Context, *DeleteTemplateRequest) (*DeleteTemplateResponse, error)

	ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error)

	UpsertTemplate(context.Context, *UpsertTemplateRequest) (*UpsertTemplateResponse, error)
}

func RegisterTemplatesHTTPServer(s http1.ServiceRegistrar, srv TemplatesHTTPServer) {
	s.RegisterService(&_HTTP_Templates_serviceDesc, srv)
}

func _HTTP_Templates_ListTemplates_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in ListTemplatesRequest

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).ListTemplates(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_Templates_UpsertTemplate_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in UpsertTemplateRequest

	if err := dec(&in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).UpsertTemplate(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_Templates_DeleteTemplateById_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in DeleteTemplateRequest

	if err := http1.BindForm(req, &in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).DeleteTemplateById(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _HTTP_Templates_serviceDesc = http1.ServiceDesc{
	ServiceName: "template.v1.Templates",
	Methods: []http1.MethodDesc{

		{
			Path:    "/templates",
			Method:  "GET",
			Handler: _HTTP_Templates_ListTemplates_0,
		},

		{
			Path:    "/templates",
			Method:  "POST",
			Handler: _HTTP_Templates_UpsertTemplate_0,
		},

		{
			Path:    "/templates",
			Method:  "DELETE",
			Handler: _HTTP_Templates_DeleteTemplateById_0,
		},
	},
	Metadata: "api/template/template.proto",
}
