// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/template/template.proto

package template

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	errors "service/api/errors"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// * Petición vacía.
type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_api_template_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_template_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_api_template_template_proto_rawDescGZIP(), []int{0}
}

// * Respuesta con la lista de plantillas.
type ListTemplatesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Templates     []*Template              `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"` // Colección de plantillas
	Meta          *errors.StandardResponse `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`           // Estado de la operación
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_api_template_template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_template_template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_api_template_template_proto_rawDescGZIP(), []int{1}
}

func (x *ListTemplatesResponse) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListTemplatesResponse) GetMeta() *errors.StandardResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

// * Cuerpo para crear/actualizar una plantilla.
type UpsertTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // 0 → crear
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // ej. Template 1 / Template 2
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTemplateRequest) Reset() {
	*x = UpsertTemplateRequest{}
	mi := &file_api_template_template_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTemplateRequest) ProtoMessage() {}

func (x *UpsertTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_template_template_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpsertTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_template_template_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertTemplateRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpsertTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// * Resultado del upsert.
type UpsertTemplateResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Template      *Template                `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"` // Plantilla creada/actualizada
	Meta          *errors.StandardResponse `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`         // Estado de la operación
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTemplateResponse) Reset() {
	*x = UpsertTemplateResponse{}
	mi := &file_api_template_template_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTemplateResponse) ProtoMessage() {}

func (x *UpsertTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_template_template_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTemplateResponse.ProtoReflect.Descriptor instead.
func (*UpsertTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_template_template_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertTemplateResponse) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *UpsertTemplateResponse) GetMeta() *errors.StandardResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

// * Petición para eliminar por ID.
type DeleteTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // ID interno
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_api_template_template_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_template_template_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_template_template_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTemplateRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// * Respuesta de eliminación.
type DeleteTemplateResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Meta          *errors.StandardResponse `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"` // Estado de la operación
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateResponse) Reset() {
	*x = DeleteTemplateResponse{}
	mi := &file_api_template_template_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateResponse) ProtoMessage() {}

func (x *DeleteTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_template_template_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateResponse.ProtoReflect.Descriptor instead.
func (*DeleteTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_template_template_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTemplateResponse) GetMeta() *errors.StandardResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

// * Plantilla de alerta/aviso.
type Template struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          *Type                  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // ej. Template 1 / Template 2
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_api_template_template_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_api_template_template_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_api_template_template_proto_rawDescGZIP(), []int{6}
}

func (x *Template) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Template) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Template) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Template) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Template) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // Type1/Type2
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_api_template_template_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_api_template_template_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_api_template_template_proto_rawDescGZIP(), []int{7}
}

func (x *Type) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Type) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Type) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Type) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_template_template_proto protoreflect.FileDescriptor

const file_api_template_template_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/template/template.proto\x12\vtemplate.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dapi/errors/error_reason.proto\"\x16\n" +
	"\x14ListTemplatesRequest\"\x81\x01\n" +
	"\x15ListTemplatesResponse\x123\n" +
	"\ttemplates\x18\x01 \x03(\v2\x15.template.v1.TemplateR\ttemplates\x123\n" +
	"\x04meta\x18\x02 \x01(\v2\x1f.errors.common.StandardResponseR\x04meta\"E\n" +
	"\x15UpsertTemplateRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\rB\x03\xe0A\x01R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\"\x80\x01\n" +
	"\x16UpsertTemplateResponse\x121\n" +
	"\btemplate\x18\x01 \x01(\v2\x15.template.v1.TemplateR\btemplate\x123\n" +
	"\x04meta\x18\x02 \x01(\v2\x1f.errors.common.StandardResponseR\x04meta\",\n" +
	"\x15DeleteTemplateRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\rB\x03\xe0A\x02R\x02id\"M\n" +
	"\x16DeleteTemplateResponse\x123\n" +
	"\x04meta\x18\x01 \x01(\v2\x1f.errors.common.StandardResponseR\x04meta\"\xcb\x01\n" +
	"\bTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12%\n" +
	"\x04type\x18\x02 \x01(\v2\x11.template.v1.TypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa0\x01\n" +
	"\x04Type\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xdc\x02\n" +
	"\tTemplates\x12j\n" +
	"\rListTemplates\x12!.template.v1.ListTemplatesRequest\x1a\".template.v1.ListTemplatesResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/templates\x12p\n" +
	"\x0eUpsertTemplate\x12\".template.v1.UpsertTemplateRequest\x1a#.template.v1.UpsertTemplateResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/templates\x12q\n" +
	"\x12DeleteTemplateById\x12\".template.v1.DeleteTemplateRequest\x1a#.template.v1.DeleteTemplateResponse\"\x12\x82\xd3\xe4\x93\x02\f*\n" +
	"/templatesBT\n" +
	" dev.kratos.api.template.templateB\x0fTemplateProtoV1P\x01Z\x1dservice/api/template;templateb\x06proto3"

var (
	file_api_template_template_proto_rawDescOnce sync.Once
	file_api_template_template_proto_rawDescData []byte
)

func file_api_template_template_proto_rawDescGZIP() []byte {
	file_api_template_template_proto_rawDescOnce.Do(func() {
		file_api_template_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_template_template_proto_rawDesc), len(file_api_template_template_proto_rawDesc)))
	})
	return file_api_template_template_proto_rawDescData
}

var file_api_template_template_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_template_template_proto_goTypes = []any{
	(*ListTemplatesRequest)(nil),    // 0: template.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),   // 1: template.v1.ListTemplatesResponse
	(*UpsertTemplateRequest)(nil),   // 2: template.v1.UpsertTemplateRequest
	(*UpsertTemplateResponse)(nil),  // 3: template.v1.UpsertTemplateResponse
	(*DeleteTemplateRequest)(nil),   // 4: template.v1.DeleteTemplateRequest
	(*DeleteTemplateResponse)(nil),  // 5: template.v1.DeleteTemplateResponse
	(*Template)(nil),                // 6: template.v1.Template
	(*Type)(nil),                    // 7: template.v1.Type
	(*errors.StandardResponse)(nil), // 8: errors.common.StandardResponse
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_api_template_template_proto_depIdxs = []int32{
	6,  // 0: template.v1.ListTemplatesResponse.templates:type_name -> template.v1.Template
	8,  // 1: template.v1.ListTemplatesResponse.meta:type_name -> errors.common.StandardResponse
	6,  // 2: template.v1.UpsertTemplateResponse.template:type_name -> template.v1.Template
	8,  // 3: template.v1.UpsertTemplateResponse.meta:type_name -> errors.common.StandardResponse
	8,  // 4: template.v1.DeleteTemplateResponse.meta:type_name -> errors.common.StandardResponse
	7,  // 5: template.v1.Template.type:type_name -> template.v1.Type
	9,  // 6: template.v1.Template.created_at:type_name -> google.protobuf.Timestamp
	9,  // 7: template.v1.Template.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 8: template.v1.Type.created_at:type_name -> google.protobuf.Timestamp
	9,  // 9: template.v1.Type.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 10: template.v1.Templates.ListTemplates:input_type -> template.v1.ListTemplatesRequest
	2,  // 11: template.v1.Templates.UpsertTemplate:input_type -> template.v1.UpsertTemplateRequest
	4,  // 12: template.v1.Templates.DeleteTemplateById:input_type -> template.v1.DeleteTemplateRequest
	1,  // 13: template.v1.Templates.ListTemplates:output_type -> template.v1.ListTemplatesResponse
	3,  // 14: template.v1.Templates.UpsertTemplate:output_type -> template.v1.UpsertTemplateResponse
	5,  // 15: template.v1.Templates.DeleteTemplateById:output_type -> template.v1.DeleteTemplateResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_template_template_proto_init() }
func file_api_template_template_proto_init() {
	if File_api_template_template_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_template_template_proto_rawDesc), len(file_api_template_template_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_template_template_proto_goTypes,
		DependencyIndexes: file_api_template_template_proto_depIdxs,
		MessageInfos:      file_api_template_template_proto_msgTypes,
	}.Build()
	File_api_template_template_proto = out.File
	file_api_template_template_proto_goTypes = nil
	file_api_template_template_proto_depIdxs = nil
}
