// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/prueba/v1/prueba.proto

package prueba

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// * Filtros de busqueda. Si vacio -> listado completo.
type FindPruebasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // filtrar por ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // filtrar por nombre
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPruebasRequest) Reset() {
	*x = FindPruebasRequest{}
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPruebasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPruebasRequest) ProtoMessage() {}

func (x *FindPruebasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPruebasRequest.ProtoReflect.Descriptor instead.
func (*FindPruebasRequest) Descriptor() ([]byte, []int) {
	return file_api_prueba_v1_prueba_proto_rawDescGZIP(), []int{0}
}

func (x *FindPruebasRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FindPruebasRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// * Respuesta con lista.
type FindPruebasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Prueba              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // coleccion de resultados
	Meta          *MetaResponse          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`   // estado de la operacion
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPruebasResponse) Reset() {
	*x = FindPruebasResponse{}
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPruebasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPruebasResponse) ProtoMessage() {}

func (x *FindPruebasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPruebasResponse.ProtoReflect.Descriptor instead.
func (*FindPruebasResponse) Descriptor() ([]byte, []int) {
	return file_api_prueba_v1_prueba_proto_rawDescGZIP(), []int{1}
}

func (x *FindPruebasResponse) GetItems() []*Prueba {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FindPruebasResponse) GetMeta() *MetaResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

// * Cuerpo para crear o actualizar.
type UpsertPruebaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 0 -> crear
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPruebaRequest) Reset() {
	*x = UpsertPruebaRequest{}
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPruebaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPruebaRequest) ProtoMessage() {}

func (x *UpsertPruebaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPruebaRequest.ProtoReflect.Descriptor instead.
func (*UpsertPruebaRequest) Descriptor() ([]byte, []int) {
	return file_api_prueba_v1_prueba_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertPruebaRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpsertPruebaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// * Resultado del upsert.
type UpsertPruebaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Prueba                `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"` // entidad creada o actualizada
	Meta          *MetaResponse          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPruebaResponse) Reset() {
	*x = UpsertPruebaResponse{}
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPruebaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPruebaResponse) ProtoMessage() {}

func (x *UpsertPruebaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPruebaResponse.ProtoReflect.Descriptor instead.
func (*UpsertPruebaResponse) Descriptor() ([]byte, []int) {
	return file_api_prueba_v1_prueba_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertPruebaResponse) GetItem() *Prueba {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *UpsertPruebaResponse) GetMeta() *MetaResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

// * Peticion para eliminar por ID.
type DeletePruebaByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // ID interno
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePruebaByIdRequest) Reset() {
	*x = DeletePruebaByIdRequest{}
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePruebaByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePruebaByIdRequest) ProtoMessage() {}

func (x *DeletePruebaByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePruebaByIdRequest.ProtoReflect.Descriptor instead.
func (*DeletePruebaByIdRequest) Descriptor() ([]byte, []int) {
	return file_api_prueba_v1_prueba_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePruebaByIdRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// * Respuesta de eliminacion.
type DeletePruebaByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MetaResponse          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePruebaByIdResponse) Reset() {
	*x = DeletePruebaByIdResponse{}
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePruebaByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePruebaByIdResponse) ProtoMessage() {}

func (x *DeletePruebaByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePruebaByIdResponse.ProtoReflect.Descriptor instead.
func (*DeletePruebaByIdResponse) Descriptor() ([]byte, []int) {
	return file_api_prueba_v1_prueba_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePruebaByIdResponse) GetMeta() *MetaResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

// * Modelo prueba. Ajusta campos al dominio.
type Prueba struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // ejemplo: "Prueba 1"
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prueba) Reset() {
	*x = Prueba{}
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prueba) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prueba) ProtoMessage() {}

func (x *Prueba) ProtoReflect() protoreflect.Message {
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prueba.ProtoReflect.Descriptor instead.
func (*Prueba) Descriptor() ([]byte, []int) {
	return file_api_prueba_v1_prueba_proto_rawDescGZIP(), []int{6}
}

func (x *Prueba) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Prueba) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Prueba) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Prueba) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_prueba_v1_prueba_proto protoreflect.FileDescriptor

const file_api_prueba_v1_prueba_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/prueba/v1/prueba.proto\x12\rapi.prueba.v1\x1a\x1aapi/prueba/v1/errors.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"B\n" +
	"\x12FindPruebasRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\rB\x03\xe0A\x01R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x01R\x04name\"s\n" +
	"\x13FindPruebasResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.api.prueba.v1.PruebaR\x05items\x12/\n" +
	"\x04meta\x18\x02 \x01(\v2\x1b.api.prueba.v1.MetaResponseR\x04meta\"C\n" +
	"\x13UpsertPruebaRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\rB\x03\xe0A\x01R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\"r\n" +
	"\x14UpsertPruebaResponse\x12)\n" +
	"\x04item\x18\x01 \x01(\v2\x15.api.prueba.v1.PruebaR\x04item\x12/\n" +
	"\x04meta\x18\x02 \x01(\v2\x1b.api.prueba.v1.MetaResponseR\x04meta\".\n" +
	"\x17DeletePruebaByIdRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\rB\x03\xe0A\x02R\x02id\"K\n" +
	"\x18DeletePruebaByIdResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.api.prueba.v1.MetaResponseR\x04meta\"\xa2\x01\n" +
	"\x06Prueba\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xdc\x02\n" +
	"\rPruebaService\x12f\n" +
	"\vFindPruebas\x12!.api.prueba.v1.FindPruebasRequest\x1a\".api.prueba.v1.FindPruebasResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/pruebas\x12l\n" +
	"\fUpsertPrueba\x12\".api.prueba.v1.UpsertPruebaRequest\x1a#.api.prueba.v1.UpsertPruebaResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/pruebas\x12u\n" +
	"\x10DeletePruebaById\x12&.api.prueba.v1.DeletePruebaByIdRequest\x1a'.api.prueba.v1.DeletePruebaByIdResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"*\b/pruebasBJ\n" +
	"\x1cdev.kratos.api.prueba.pruebaB\rPruebaProtoV1P\x01Z\x19service/api/prueba;pruebab\x06proto3"

var (
	file_api_prueba_v1_prueba_proto_rawDescOnce sync.Once
	file_api_prueba_v1_prueba_proto_rawDescData []byte
)

func file_api_prueba_v1_prueba_proto_rawDescGZIP() []byte {
	file_api_prueba_v1_prueba_proto_rawDescOnce.Do(func() {
		file_api_prueba_v1_prueba_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_prueba_v1_prueba_proto_rawDesc), len(file_api_prueba_v1_prueba_proto_rawDesc)))
	})
	return file_api_prueba_v1_prueba_proto_rawDescData
}

var file_api_prueba_v1_prueba_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_prueba_v1_prueba_proto_goTypes = []any{
	(*FindPruebasRequest)(nil),       // 0: api.prueba.v1.FindPruebasRequest
	(*FindPruebasResponse)(nil),      // 1: api.prueba.v1.FindPruebasResponse
	(*UpsertPruebaRequest)(nil),      // 2: api.prueba.v1.UpsertPruebaRequest
	(*UpsertPruebaResponse)(nil),     // 3: api.prueba.v1.UpsertPruebaResponse
	(*DeletePruebaByIdRequest)(nil),  // 4: api.prueba.v1.DeletePruebaByIdRequest
	(*DeletePruebaByIdResponse)(nil), // 5: api.prueba.v1.DeletePruebaByIdResponse
	(*Prueba)(nil),                   // 6: api.prueba.v1.Prueba
	(*MetaResponse)(nil),             // 7: api.prueba.v1.MetaResponse
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
}
var file_api_prueba_v1_prueba_proto_depIdxs = []int32{
	6,  // 0: api.prueba.v1.FindPruebasResponse.items:type_name -> api.prueba.v1.Prueba
	7,  // 1: api.prueba.v1.FindPruebasResponse.meta:type_name -> api.prueba.v1.MetaResponse
	6,  // 2: api.prueba.v1.UpsertPruebaResponse.item:type_name -> api.prueba.v1.Prueba
	7,  // 3: api.prueba.v1.UpsertPruebaResponse.meta:type_name -> api.prueba.v1.MetaResponse
	7,  // 4: api.prueba.v1.DeletePruebaByIdResponse.meta:type_name -> api.prueba.v1.MetaResponse
	8,  // 5: api.prueba.v1.Prueba.created_at:type_name -> google.protobuf.Timestamp
	8,  // 6: api.prueba.v1.Prueba.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: api.prueba.v1.PruebaService.FindPruebas:input_type -> api.prueba.v1.FindPruebasRequest
	2,  // 8: api.prueba.v1.PruebaService.UpsertPrueba:input_type -> api.prueba.v1.UpsertPruebaRequest
	4,  // 9: api.prueba.v1.PruebaService.DeletePruebaById:input_type -> api.prueba.v1.DeletePruebaByIdRequest
	1,  // 10: api.prueba.v1.PruebaService.FindPruebas:output_type -> api.prueba.v1.FindPruebasResponse
	3,  // 11: api.prueba.v1.PruebaService.UpsertPrueba:output_type -> api.prueba.v1.UpsertPruebaResponse
	5,  // 12: api.prueba.v1.PruebaService.DeletePruebaById:output_type -> api.prueba.v1.DeletePruebaByIdResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_prueba_v1_prueba_proto_init() }
func file_api_prueba_v1_prueba_proto_init() {
	if File_api_prueba_v1_prueba_proto != nil {
		return
	}
	file_api_prueba_v1_errors_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_prueba_v1_prueba_proto_rawDesc), len(file_api_prueba_v1_prueba_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_prueba_v1_prueba_proto_goTypes,
		DependencyIndexes: file_api_prueba_v1_prueba_proto_depIdxs,
		MessageInfos:      file_api_prueba_v1_prueba_proto_msgTypes,
	}.Build()
	File_api_prueba_v1_prueba_proto = out.File
	file_api_prueba_v1_prueba_proto_goTypes = nil
	file_api_prueba_v1_prueba_proto_depIdxs = nil
}
