// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/prueba/v1/prueba.proto

package prueba

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindPruebasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPruebasRequest) Reset() {
	*x = FindPruebasRequest{}
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPruebasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPruebasRequest) ProtoMessage() {}

func (x *FindPruebasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPruebasRequest.ProtoReflect.Descriptor instead.
func (*FindPruebasRequest) Descriptor() ([]byte, []int) {
	return file_api_prueba_v1_prueba_proto_rawDescGZIP(), []int{0}
}

func (x *FindPruebasRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FindPruebasRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FindPruebasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Prueba              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Meta          *MetaResponse          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPruebasResponse) Reset() {
	*x = FindPruebasResponse{}
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPruebasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPruebasResponse) ProtoMessage() {}

func (x *FindPruebasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPruebasResponse.ProtoReflect.Descriptor instead.
func (*FindPruebasResponse) Descriptor() ([]byte, []int) {
	return file_api_prueba_v1_prueba_proto_rawDescGZIP(), []int{1}
}

func (x *FindPruebasResponse) GetItems() []*Prueba {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FindPruebasResponse) GetMeta() *MetaResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

type UpsertPruebaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPruebaRequest) Reset() {
	*x = UpsertPruebaRequest{}
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPruebaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPruebaRequest) ProtoMessage() {}

func (x *UpsertPruebaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPruebaRequest.ProtoReflect.Descriptor instead.
func (*UpsertPruebaRequest) Descriptor() ([]byte, []int) {
	return file_api_prueba_v1_prueba_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertPruebaRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpsertPruebaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpsertPruebaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Prueba                `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Meta          *MetaResponse          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPruebaResponse) Reset() {
	*x = UpsertPruebaResponse{}
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPruebaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPruebaResponse) ProtoMessage() {}

func (x *UpsertPruebaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPruebaResponse.ProtoReflect.Descriptor instead.
func (*UpsertPruebaResponse) Descriptor() ([]byte, []int) {
	return file_api_prueba_v1_prueba_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertPruebaResponse) GetItem() *Prueba {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *UpsertPruebaResponse) GetMeta() *MetaResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Prueba struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prueba) Reset() {
	*x = Prueba{}
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prueba) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prueba) ProtoMessage() {}

func (x *Prueba) ProtoReflect() protoreflect.Message {
	mi := &file_api_prueba_v1_prueba_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prueba.ProtoReflect.Descriptor instead.
func (*Prueba) Descriptor() ([]byte, []int) {
	return file_api_prueba_v1_prueba_proto_rawDescGZIP(), []int{4}
}

func (x *Prueba) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Prueba) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Prueba) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Prueba) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_prueba_v1_prueba_proto protoreflect.FileDescriptor

const file_api_prueba_v1_prueba_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/prueba/v1/prueba.proto\x12\rapi.prueba.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1aapi/prueba/v1/errors.proto\"B\n" +
	"\x12FindPruebasRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\rB\x03\xe0A\x01R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x01R\x04name\"s\n" +
	"\x13FindPruebasResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.api.prueba.v1.PruebaR\x05items\x12/\n" +
	"\x04meta\x18\x02 \x01(\v2\x1b.api.prueba.v1.MetaResponseR\x04meta\"C\n" +
	"\x13UpsertPruebaRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\rB\x03\xe0A\x01R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\"r\n" +
	"\x14UpsertPruebaResponse\x12)\n" +
	"\x04item\x18\x01 \x01(\v2\x15.api.prueba.v1.PruebaR\x04item\x12/\n" +
	"\x04meta\x18\x02 \x01(\v2\x1b.api.prueba.v1.MetaResponseR\x04meta\"\xa2\x01\n" +
	"\x06Prueba\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xeb\x01\n" +
	"\x0fPruebav1Service\x12h\n" +
	"\vFindPruebas\x12!.api.prueba.v1.FindPruebasRequest\x1a\".api.prueba.v1.FindPruebasResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/prueba\x12n\n" +
	"\fUpsertPrueba\x12\".api.prueba.v1.UpsertPruebaRequest\x1a#.api.prueba.v1.UpsertPruebaResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/pruebaBJ\n" +
	"\x1cdev.kratos.api.prueba.pruebaB\rPruebaProtoV1P\x01Z\x19service/api/prueba;pruebab\x06proto3"

var (
	file_api_prueba_v1_prueba_proto_rawDescOnce sync.Once
	file_api_prueba_v1_prueba_proto_rawDescData []byte
)

func file_api_prueba_v1_prueba_proto_rawDescGZIP() []byte {
	file_api_prueba_v1_prueba_proto_rawDescOnce.Do(func() {
		file_api_prueba_v1_prueba_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_prueba_v1_prueba_proto_rawDesc), len(file_api_prueba_v1_prueba_proto_rawDesc)))
	})
	return file_api_prueba_v1_prueba_proto_rawDescData
}

var file_api_prueba_v1_prueba_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_prueba_v1_prueba_proto_goTypes = []any{
	(*FindPruebasRequest)(nil),    // 0: api.prueba.v1.FindPruebasRequest
	(*FindPruebasResponse)(nil),   // 1: api.prueba.v1.FindPruebasResponse
	(*UpsertPruebaRequest)(nil),   // 2: api.prueba.v1.UpsertPruebaRequest
	(*UpsertPruebaResponse)(nil),  // 3: api.prueba.v1.UpsertPruebaResponse
	(*Prueba)(nil),                // 4: api.prueba.v1.Prueba
	(*MetaResponse)(nil),          // 5: api.prueba.v1.MetaResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_api_prueba_v1_prueba_proto_depIdxs = []int32{
	4, // 0: api.prueba.v1.FindPruebasResponse.items:type_name -> api.prueba.v1.Prueba
	5, // 1: api.prueba.v1.FindPruebasResponse.meta:type_name -> api.prueba.v1.MetaResponse
	4, // 2: api.prueba.v1.UpsertPruebaResponse.item:type_name -> api.prueba.v1.Prueba
	5, // 3: api.prueba.v1.UpsertPruebaResponse.meta:type_name -> api.prueba.v1.MetaResponse
	6, // 4: api.prueba.v1.Prueba.created_at:type_name -> google.protobuf.Timestamp
	6, // 5: api.prueba.v1.Prueba.updated_at:type_name -> google.protobuf.Timestamp
	0, // 6: api.prueba.v1.Pruebav1Service.FindPruebas:input_type -> api.prueba.v1.FindPruebasRequest
	2, // 7: api.prueba.v1.Pruebav1Service.UpsertPrueba:input_type -> api.prueba.v1.UpsertPruebaRequest
	1, // 8: api.prueba.v1.Pruebav1Service.FindPruebas:output_type -> api.prueba.v1.FindPruebasResponse
	3, // 9: api.prueba.v1.Pruebav1Service.UpsertPrueba:output_type -> api.prueba.v1.UpsertPruebaResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_prueba_v1_prueba_proto_init() }
func file_api_prueba_v1_prueba_proto_init() {
	if File_api_prueba_v1_prueba_proto != nil {
		return
	}
	file_api_prueba_v1_errors_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_prueba_v1_prueba_proto_rawDesc), len(file_api_prueba_v1_prueba_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_prueba_v1_prueba_proto_goTypes,
		DependencyIndexes: file_api_prueba_v1_prueba_proto_depIdxs,
		MessageInfos:      file_api_prueba_v1_prueba_proto_msgTypes,
	}.Build()
	File_api_prueba_v1_prueba_proto = out.File
	file_api_prueba_v1_prueba_proto_goTypes = nil
	file_api_prueba_v1_prueba_proto_depIdxs = nil
}
