// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/example/v1/example.proto

package example

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockRequest) Reset() {
	*x = MockRequest{}
	mi := &file_api_example_v1_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockRequest) ProtoMessage() {}

func (x *MockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_v1_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockRequest.ProtoReflect.Descriptor instead.
func (*MockRequest) Descriptor() ([]byte, []int) {
	return file_api_example_v1_example_proto_rawDescGZIP(), []int{0}
}

type MockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // e.g. ""pong""
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockResponse) Reset() {
	*x = MockResponse{}
	mi := &file_api_example_v1_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockResponse) ProtoMessage() {}

func (x *MockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_v1_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockResponse.ProtoReflect.Descriptor instead.
func (*MockResponse) Descriptor() ([]byte, []int) {
	return file_api_example_v1_example_proto_rawDescGZIP(), []int{1}
}

func (x *MockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Example struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_api_example_v1_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_v1_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_api_example_v1_example_proto_rawDescGZIP(), []int{2}
}

func (x *Example) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Example) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Example) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Example) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_example_v1_example_proto protoreflect.FileDescriptor

const file_api_example_v1_example_proto_rawDesc = "" +
	"\n" +
	"\x1capi/example/v1/example.proto\x12\x0eapi.example.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"\r\n" +
	"\vMockRequest\"(\n" +
	"\fMockResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xa3\x01\n" +
	"\aExample\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2o\n" +
	"\x10Examplev1Service\x12[\n" +
	"\x04Mock\x12\x1b.api.example.v1.MockRequest\x1a\x1c.api.example.v1.MockResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/example/mockBO\n" +
	"\x1edev.kratos.api.example.exampleB\x0eExampleProtoV1P\x01Z\x1bservice/api/example;exampleb\x06proto3"

var (
	file_api_example_v1_example_proto_rawDescOnce sync.Once
	file_api_example_v1_example_proto_rawDescData []byte
)

func file_api_example_v1_example_proto_rawDescGZIP() []byte {
	file_api_example_v1_example_proto_rawDescOnce.Do(func() {
		file_api_example_v1_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_example_v1_example_proto_rawDesc), len(file_api_example_v1_example_proto_rawDesc)))
	})
	return file_api_example_v1_example_proto_rawDescData
}

var file_api_example_v1_example_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_example_v1_example_proto_goTypes = []any{
	(*MockRequest)(nil),           // 0: api.example.v1.MockRequest
	(*MockResponse)(nil),          // 1: api.example.v1.MockResponse
	(*Example)(nil),               // 2: api.example.v1.Example
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_example_v1_example_proto_depIdxs = []int32{
	3, // 0: api.example.v1.Example.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: api.example.v1.Example.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: api.example.v1.Examplev1Service.Mock:input_type -> api.example.v1.MockRequest
	1, // 3: api.example.v1.Examplev1Service.Mock:output_type -> api.example.v1.MockResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_example_v1_example_proto_init() }
func file_api_example_v1_example_proto_init() {
	if File_api_example_v1_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_example_v1_example_proto_rawDesc), len(file_api_example_v1_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_example_v1_example_proto_goTypes,
		DependencyIndexes: file_api_example_v1_example_proto_depIdxs,
		MessageInfos:      file_api_example_v1_example_proto_msgTypes,
	}.Build()
	File_api_example_v1_example_proto = out.File
	file_api_example_v1_example_proto_goTypes = nil
	file_api_example_v1_example_proto_depIdxs = nil
}
