// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/example/v1/example.proto

package example

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// * Petición vacía.
type ListExamplesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExamplesRequest) Reset() {
	*x = ListExamplesRequest{}
	mi := &file_api_example_v1_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExamplesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExamplesRequest) ProtoMessage() {}

func (x *ListExamplesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_v1_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExamplesRequest.ProtoReflect.Descriptor instead.
func (*ListExamplesRequest) Descriptor() ([]byte, []int) {
	return file_api_example_v1_example_proto_rawDescGZIP(), []int{0}
}

// * Respuesta con la lista de plantillas.
type ListExamplesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Examples      []*Example             `protobuf:"bytes,1,rep,name=examples,proto3" json:"examples,omitempty"` // Colección de ejemplos
	Meta          *MetaResponse          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`         // Estado de la operación
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExamplesResponse) Reset() {
	*x = ListExamplesResponse{}
	mi := &file_api_example_v1_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExamplesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExamplesResponse) ProtoMessage() {}

func (x *ListExamplesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_v1_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExamplesResponse.ProtoReflect.Descriptor instead.
func (*ListExamplesResponse) Descriptor() ([]byte, []int) {
	return file_api_example_v1_example_proto_rawDescGZIP(), []int{1}
}

func (x *ListExamplesResponse) GetExamples() []*Example {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *ListExamplesResponse) GetMeta() *MetaResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

// * Cuerpo para crear/actualizar una plantilla.
type UpsertExampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // 0 → crear
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // ej. Example 1 / Example 2
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertExampleRequest) Reset() {
	*x = UpsertExampleRequest{}
	mi := &file_api_example_v1_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertExampleRequest) ProtoMessage() {}

func (x *UpsertExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_v1_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertExampleRequest.ProtoReflect.Descriptor instead.
func (*UpsertExampleRequest) Descriptor() ([]byte, []int) {
	return file_api_example_v1_example_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertExampleRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpsertExampleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// * Resultado del upsert.
type UpsertExampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Example       *Example               `protobuf:"bytes,1,opt,name=example,proto3" json:"example,omitempty"` // Ejemplo creado/actualizado
	Meta          *MetaResponse          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`       // Estado de la operación
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertExampleResponse) Reset() {
	*x = UpsertExampleResponse{}
	mi := &file_api_example_v1_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertExampleResponse) ProtoMessage() {}

func (x *UpsertExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_v1_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertExampleResponse.ProtoReflect.Descriptor instead.
func (*UpsertExampleResponse) Descriptor() ([]byte, []int) {
	return file_api_example_v1_example_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertExampleResponse) GetExample() *Example {
	if x != nil {
		return x.Example
	}
	return nil
}

func (x *UpsertExampleResponse) GetMeta() *MetaResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

// * Petición para eliminar por ID.
type DeleteExampleByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // ID interno
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExampleByIdRequest) Reset() {
	*x = DeleteExampleByIdRequest{}
	mi := &file_api_example_v1_example_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExampleByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExampleByIdRequest) ProtoMessage() {}

func (x *DeleteExampleByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_v1_example_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExampleByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteExampleByIdRequest) Descriptor() ([]byte, []int) {
	return file_api_example_v1_example_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteExampleByIdRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// * Respuesta de eliminación.
type DeleteExampleByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MetaResponse          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"` // Estado de la operación
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExampleByIdResponse) Reset() {
	*x = DeleteExampleByIdResponse{}
	mi := &file_api_example_v1_example_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExampleByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExampleByIdResponse) ProtoMessage() {}

func (x *DeleteExampleByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_v1_example_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExampleByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteExampleByIdResponse) Descriptor() ([]byte, []int) {
	return file_api_example_v1_example_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteExampleByIdResponse) GetMeta() *MetaResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

// * Ejemplo de alerta/aviso.
type Example struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          *TypeExample           `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // ej. Example 1 / Example 2
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_api_example_v1_example_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_v1_example_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_api_example_v1_example_proto_rawDescGZIP(), []int{6}
}

func (x *Example) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Example) GetType() *TypeExample {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Example) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Example) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Example) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TypeExample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // Type1/Type2
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeExample) Reset() {
	*x = TypeExample{}
	mi := &file_api_example_v1_example_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeExample) ProtoMessage() {}

func (x *TypeExample) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_v1_example_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeExample.ProtoReflect.Descriptor instead.
func (*TypeExample) Descriptor() ([]byte, []int) {
	return file_api_example_v1_example_proto_rawDescGZIP(), []int{7}
}

func (x *TypeExample) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TypeExample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeExample) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TypeExample) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_example_v1_example_proto protoreflect.FileDescriptor

const file_api_example_v1_example_proto_rawDesc = "" +
	"\n" +
	"\x1capi/example/v1/example.proto\x12\x0eapi.example.v1\x1a\x1bapi/example/v1/errors.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x15\n" +
	"\x13ListExamplesRequest\"}\n" +
	"\x14ListExamplesResponse\x123\n" +
	"\bexamples\x18\x01 \x03(\v2\x17.api.example.v1.ExampleR\bexamples\x120\n" +
	"\x04meta\x18\x02 \x01(\v2\x1c.api.example.v1.MetaResponseR\x04meta\"D\n" +
	"\x14UpsertExampleRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\rB\x03\xe0A\x01R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\"|\n" +
	"\x15UpsertExampleResponse\x121\n" +
	"\aexample\x18\x01 \x01(\v2\x17.api.example.v1.ExampleR\aexample\x120\n" +
	"\x04meta\x18\x02 \x01(\v2\x1c.api.example.v1.MetaResponseR\x04meta\"/\n" +
	"\x18DeleteExampleByIdRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\rB\x03\xe0A\x02R\x02id\"M\n" +
	"\x19DeleteExampleByIdResponse\x120\n" +
	"\x04meta\x18\x01 \x01(\v2\x1c.api.example.v1.MetaResponseR\x04meta\"\xd4\x01\n" +
	"\aExample\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12/\n" +
	"\x04type\x18\x02 \x01(\v2\x1b.api.example.v1.TypeExampleR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa7\x01\n" +
	"\vTypeExample\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xf7\x02\n" +
	"\x10Examplev1Service\x12n\n" +
	"\fListExamples\x12#.api.example.v1.ListExamplesRequest\x1a$.api.example.v1.ListExamplesResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/example\x12t\n" +
	"\rUpsertExample\x12$.api.example.v1.UpsertExampleRequest\x1a%.api.example.v1.UpsertExampleResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/example\x12}\n" +
	"\x11DeleteExampleById\x12(.api.example.v1.DeleteExampleByIdRequest\x1a).api.example.v1.DeleteExampleByIdResponse\"\x13\x82\xd3\xe4\x93\x02\r*\v/v1/exampleBO\n" +
	"\x1edev.kratos.api.example.exampleB\x0eExampleProtoV1P\x01Z\x1bservice/api/example;exampleb\x06proto3"

var (
	file_api_example_v1_example_proto_rawDescOnce sync.Once
	file_api_example_v1_example_proto_rawDescData []byte
)

func file_api_example_v1_example_proto_rawDescGZIP() []byte {
	file_api_example_v1_example_proto_rawDescOnce.Do(func() {
		file_api_example_v1_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_example_v1_example_proto_rawDesc), len(file_api_example_v1_example_proto_rawDesc)))
	})
	return file_api_example_v1_example_proto_rawDescData
}

var file_api_example_v1_example_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_example_v1_example_proto_goTypes = []any{
	(*ListExamplesRequest)(nil),       // 0: api.example.v1.ListExamplesRequest
	(*ListExamplesResponse)(nil),      // 1: api.example.v1.ListExamplesResponse
	(*UpsertExampleRequest)(nil),      // 2: api.example.v1.UpsertExampleRequest
	(*UpsertExampleResponse)(nil),     // 3: api.example.v1.UpsertExampleResponse
	(*DeleteExampleByIdRequest)(nil),  // 4: api.example.v1.DeleteExampleByIdRequest
	(*DeleteExampleByIdResponse)(nil), // 5: api.example.v1.DeleteExampleByIdResponse
	(*Example)(nil),                   // 6: api.example.v1.Example
	(*TypeExample)(nil),               // 7: api.example.v1.TypeExample
	(*MetaResponse)(nil),              // 8: api.example.v1.MetaResponse
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
}
var file_api_example_v1_example_proto_depIdxs = []int32{
	6,  // 0: api.example.v1.ListExamplesResponse.examples:type_name -> api.example.v1.Example
	8,  // 1: api.example.v1.ListExamplesResponse.meta:type_name -> api.example.v1.MetaResponse
	6,  // 2: api.example.v1.UpsertExampleResponse.example:type_name -> api.example.v1.Example
	8,  // 3: api.example.v1.UpsertExampleResponse.meta:type_name -> api.example.v1.MetaResponse
	8,  // 4: api.example.v1.DeleteExampleByIdResponse.meta:type_name -> api.example.v1.MetaResponse
	7,  // 5: api.example.v1.Example.type:type_name -> api.example.v1.TypeExample
	9,  // 6: api.example.v1.Example.created_at:type_name -> google.protobuf.Timestamp
	9,  // 7: api.example.v1.Example.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 8: api.example.v1.TypeExample.created_at:type_name -> google.protobuf.Timestamp
	9,  // 9: api.example.v1.TypeExample.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 10: api.example.v1.Examplev1Service.ListExamples:input_type -> api.example.v1.ListExamplesRequest
	2,  // 11: api.example.v1.Examplev1Service.UpsertExample:input_type -> api.example.v1.UpsertExampleRequest
	4,  // 12: api.example.v1.Examplev1Service.DeleteExampleById:input_type -> api.example.v1.DeleteExampleByIdRequest
	1,  // 13: api.example.v1.Examplev1Service.ListExamples:output_type -> api.example.v1.ListExamplesResponse
	3,  // 14: api.example.v1.Examplev1Service.UpsertExample:output_type -> api.example.v1.UpsertExampleResponse
	5,  // 15: api.example.v1.Examplev1Service.DeleteExampleById:output_type -> api.example.v1.DeleteExampleByIdResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_example_v1_example_proto_init() }
func file_api_example_v1_example_proto_init() {
	if File_api_example_v1_example_proto != nil {
		return
	}
	file_api_example_v1_errors_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_example_v1_example_proto_rawDesc), len(file_api_example_v1_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_example_v1_example_proto_goTypes,
		DependencyIndexes: file_api_example_v1_example_proto_depIdxs,
		MessageInfos:      file_api_example_v1_example_proto_msgTypes,
	}.Build()
	File_api_example_v1_example_proto = out.File
	file_api_example_v1_example_proto_goTypes = nil
	file_api_example_v1_example_proto_depIdxs = nil
}
