// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/example/v1/example.proto

package example

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Examplev1Service_Mock_FullMethodName = "/api.example.v1.Examplev1Service/Mock"
)

// Examplev1ServiceClient is the client API for Examplev1Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Examplev1Service: generated with ops=[]
type Examplev1ServiceClient interface {
	// Mock endpoint (no ops selected)
	Mock(ctx context.Context, in *MockRequest, opts ...grpc.CallOption) (*MockResponse, error)
}

type examplev1ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExamplev1ServiceClient(cc grpc.ClientConnInterface) Examplev1ServiceClient {
	return &examplev1ServiceClient{cc}
}

func (c *examplev1ServiceClient) Mock(ctx context.Context, in *MockRequest, opts ...grpc.CallOption) (*MockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MockResponse)
	err := c.cc.Invoke(ctx, Examplev1Service_Mock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Examplev1ServiceServer is the server API for Examplev1Service service.
// All implementations must embed UnimplementedExamplev1ServiceServer
// for forward compatibility.
//
// Examplev1Service: generated with ops=[]
type Examplev1ServiceServer interface {
	// Mock endpoint (no ops selected)
	Mock(context.Context, *MockRequest) (*MockResponse, error)
	mustEmbedUnimplementedExamplev1ServiceServer()
}

// UnimplementedExamplev1ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExamplev1ServiceServer struct{}

func (UnimplementedExamplev1ServiceServer) Mock(context.Context, *MockRequest) (*MockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mock not implemented")
}
func (UnimplementedExamplev1ServiceServer) mustEmbedUnimplementedExamplev1ServiceServer() {}
func (UnimplementedExamplev1ServiceServer) testEmbeddedByValue()                          {}

// UnsafeExamplev1ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Examplev1ServiceServer will
// result in compilation errors.
type UnsafeExamplev1ServiceServer interface {
	mustEmbedUnimplementedExamplev1ServiceServer()
}

func RegisterExamplev1ServiceServer(s grpc.ServiceRegistrar, srv Examplev1ServiceServer) {
	// If the following call pancis, it indicates UnimplementedExamplev1ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Examplev1Service_ServiceDesc, srv)
}

func _Examplev1Service_Mock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Examplev1ServiceServer).Mock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Examplev1Service_Mock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Examplev1ServiceServer).Mock(ctx, req.(*MockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Examplev1Service_ServiceDesc is the grpc.ServiceDesc for Examplev1Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Examplev1Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.example.v1.Examplev1Service",
	HandlerType: (*Examplev1ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mock",
			Handler:    _Examplev1Service_Mock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/example/v1/example.proto",
}
