// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             (unknown)
// source: api/example/v1/template.proto

package example

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationExamplev1ServiceDeleteExampleById = "/api.example.v1.Examplev1Service/DeleteExampleById"
const OperationExamplev1ServiceListExamples = "/api.example.v1.Examplev1Service/ListExamples"
const OperationExamplev1ServiceUpsertExample = "/api.example.v1.Examplev1Service/UpsertExample"

type Examplev1ServiceHTTPServer interface {
	// DeleteExampleById* Elimina una plantilla por ID.
	//
	// **Descripción**
	// Borra la plantilla indicada por `id`.
	//
	// **Parámetros (query)**
	// - `id` (**obligatorio**): ID interno
	//
	// **Respuestas**
	// - `200 OK`: `meta.code = OK`
	// - `200` con error lógico: `meta.code != OK` (p. ej., ID inexistente)
	//
	// **Ejemplos**
	// `DELETE /example?id=123`
	DeleteExampleById(context.Context, *DeleteExampleByIdRequest) (*DeleteExampleByIdResponse, error)
	// ListExamples* Lista todas las plantillas.
	//
	// **Descripción**
	// Devuelve el catálogo completo de plantillas definidas.
	//
	// **Parámetros**
	// _(sin parámetros)_
	//
	// **Respuestas**
	// - `200 OK`: `examples` + `meta.code = OK`
	// - `200` con error lógico: `meta.code != OK` y `meta.message`
	//
	// **Ejemplos**
	// `GET /example`
	ListExamples(context.Context, *ListExamplesRequest) (*ListExamplesResponse, error)
	// UpsertExample* Crea o actualiza una plantilla (upsert).
	//
	// **Descripción**
	// Si `id` es `0` o no se envía → crea; si `id` > 0 → actualiza.
	//
	// **Parámetros (body JSON)**
	// - `id` (opcional, 0=create)
	// - `name` (**obligatorio**)
	//
	// **Respuestas**
	// - `200 OK`: `example` resultante + `meta.code = OK`
	// - `200` con error lógico: validación, duplicidad de `name`, etc.
	//
	// **Ejemplos**
	// `POST /example`
	// Body: `{ "name":"Example 1" }`
	UpsertExample(context.Context, *UpsertExampleRequest) (*UpsertExampleResponse, error)
}

func RegisterExamplev1ServiceHTTPServer(s *http.Server, srv Examplev1ServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/example", _Examplev1Service_ListExamples0_HTTP_Handler(srv))
	r.POST("/v1/example", _Examplev1Service_UpsertExample0_HTTP_Handler(srv))
	r.DELETE("/v1/example", _Examplev1Service_DeleteExampleById0_HTTP_Handler(srv))
}

func _Examplev1Service_ListExamples0_HTTP_Handler(srv Examplev1ServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListExamplesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExamplev1ServiceListExamples)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListExamples(ctx, req.(*ListExamplesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListExamplesResponse)
		return ctx.Result(200, reply)
	}
}

func _Examplev1Service_UpsertExample0_HTTP_Handler(srv Examplev1ServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpsertExampleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExamplev1ServiceUpsertExample)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpsertExample(ctx, req.(*UpsertExampleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpsertExampleResponse)
		return ctx.Result(200, reply)
	}
}

func _Examplev1Service_DeleteExampleById0_HTTP_Handler(srv Examplev1ServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteExampleByIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExamplev1ServiceDeleteExampleById)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteExampleById(ctx, req.(*DeleteExampleByIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteExampleByIdResponse)
		return ctx.Result(200, reply)
	}
}

type Examplev1ServiceHTTPClient interface {
	// DeleteExampleById* Elimina una plantilla por ID.
	//
	// **Descripción**
	// Borra la plantilla indicada por `id`.
	//
	// **Parámetros (query)**
	// - `id` (**obligatorio**): ID interno
	//
	// **Respuestas**
	// - `200 OK`: `meta.code = OK`
	// - `200` con error lógico: `meta.code != OK` (p. ej., ID inexistente)
	//
	// **Ejemplos**
	// `DELETE /example?id=123`
	DeleteExampleById(ctx context.Context, req *DeleteExampleByIdRequest, opts ...http.CallOption) (rsp *DeleteExampleByIdResponse, err error)
	// ListExamples* Lista todas las plantillas.
	//
	// **Descripción**
	// Devuelve el catálogo completo de plantillas definidas.
	//
	// **Parámetros**
	// _(sin parámetros)_
	//
	// **Respuestas**
	// - `200 OK`: `examples` + `meta.code = OK`
	// - `200` con error lógico: `meta.code != OK` y `meta.message`
	//
	// **Ejemplos**
	// `GET /example`
	ListExamples(ctx context.Context, req *ListExamplesRequest, opts ...http.CallOption) (rsp *ListExamplesResponse, err error)
	// UpsertExample* Crea o actualiza una plantilla (upsert).
	//
	// **Descripción**
	// Si `id` es `0` o no se envía → crea; si `id` > 0 → actualiza.
	//
	// **Parámetros (body JSON)**
	// - `id` (opcional, 0=create)
	// - `name` (**obligatorio**)
	//
	// **Respuestas**
	// - `200 OK`: `example` resultante + `meta.code = OK`
	// - `200` con error lógico: validación, duplicidad de `name`, etc.
	//
	// **Ejemplos**
	// `POST /example`
	// Body: `{ "name":"Example 1" }`
	UpsertExample(ctx context.Context, req *UpsertExampleRequest, opts ...http.CallOption) (rsp *UpsertExampleResponse, err error)
}

type Examplev1ServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewExamplev1ServiceHTTPClient(client *http.Client) Examplev1ServiceHTTPClient {
	return &Examplev1ServiceHTTPClientImpl{client}
}

// DeleteExampleById* Elimina una plantilla por ID.
//
// **Descripción**
// Borra la plantilla indicada por `id`.
//
// **Parámetros (query)**
// - `id` (**obligatorio**): ID interno
//
// **Respuestas**
// - `200 OK`: `meta.code = OK`
// - `200` con error lógico: `meta.code != OK` (p. ej., ID inexistente)
//
// **Ejemplos**
// `DELETE /example?id=123`
func (c *Examplev1ServiceHTTPClientImpl) DeleteExampleById(ctx context.Context, in *DeleteExampleByIdRequest, opts ...http.CallOption) (*DeleteExampleByIdResponse, error) {
	var out DeleteExampleByIdResponse
	pattern := "/v1/example"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationExamplev1ServiceDeleteExampleById))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListExamples* Lista todas las plantillas.
//
// **Descripción**
// Devuelve el catálogo completo de plantillas definidas.
//
// **Parámetros**
// _(sin parámetros)_
//
// **Respuestas**
// - `200 OK`: `examples` + `meta.code = OK`
// - `200` con error lógico: `meta.code != OK` y `meta.message`
//
// **Ejemplos**
// `GET /example`
func (c *Examplev1ServiceHTTPClientImpl) ListExamples(ctx context.Context, in *ListExamplesRequest, opts ...http.CallOption) (*ListExamplesResponse, error) {
	var out ListExamplesResponse
	pattern := "/v1/example"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationExamplev1ServiceListExamples))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpsertExample* Crea o actualiza una plantilla (upsert).
//
// **Descripción**
// Si `id` es `0` o no se envía → crea; si `id` > 0 → actualiza.
//
// **Parámetros (body JSON)**
// - `id` (opcional, 0=create)
// - `name` (**obligatorio**)
//
// **Respuestas**
// - `200 OK`: `example` resultante + `meta.code = OK`
// - `200` con error lógico: validación, duplicidad de `name`, etc.
//
// **Ejemplos**
// `POST /example`
// Body: `{ "name":"Example 1" }`
func (c *Examplev1ServiceHTTPClientImpl) UpsertExample(ctx context.Context, in *UpsertExampleRequest, opts ...http.CallOption) (*UpsertExampleResponse, error) {
	var out UpsertExampleResponse
	pattern := "/v1/example"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationExamplev1ServiceUpsertExample))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
