name: PR Check

on:
  pull_request:
    branches: [ "main", "master" ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'service/**'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  call-org-pr-check:
    uses: liftelimasd/.github/.github/workflows/pr-check.yml@main
    with:
      go_version:  "1.25.0"
      working_dir: "./service"
      run_tests:   false # true - pass tests (if you want to pass tests)
      build_smoke: false # true - build and run smoke tests (if you want to build and run smoke tests (for pass))